export const FETCHING_DATA_ARTICLE = 'FETCHING_DATA_ARTICLE';
export const FETCHING_DATA_ARTICLE_SUCCESS = 'FETCHING_DATA_ARTICLE_SUCCESS';
export const FETCHING_DATA_ARTICLE_FAILURE = 'FETCHING_DATA_ARTICLE_FAILURE';

export const FETCHING_DATA_BOOK = 'FETCHING_DATA_BOOK';
export const FETCHING_DATA_BOOK_SUCCESS = 'FETCHING_DATA_BOOK_SUCCESS';
export const FETCHING_DATA_BOOK_FAILURE = 'FETCHING_DATA_BOOK_FAILURE';